# A summary of data files------------------------------
  # 1. all.RData:
      # Generated by: Data.import.MOWL.R
      # Data frame included:
        # all0: Original MOWL data with Total, SSI only, SSDI only, SSI, SSDI applications at national  and state levels
        # all : The same as all0, but all data entries are adjusted for the length of "SSA working month"
  
  # 2. emply.RData
      # generated by: Data.import.BLS.R
      # Dataframe:
        # emply: Sesonally adjusted and unadjusted series of unemployment rate, -
        #        unemployment, employment, and labor force, at state and national level. 
      #Note: all types of national levels are the same: the original data from BLS that is -
        #        calculated based on all states. 
 
  # 3. panel.RData
      # Generated by Data.Combine.R
      # Dataframe:
        # Panel: Combine data from "all0" and "all" in "all.RData" and "emply" in "emply.RData",
        #        log, log difference, and lags are generated. 


source("General.R")

load("Data/all.RData")
load("Data/emply.RData")
load("Data/data_UI_SSA.RData")


data_UI_SSA <- 
  dplyr::select(data_UI_SSA, State = state, Cal.Year = year, Month = month, UIIC, UICC, UIIC_unadj, UICC_unadj)


# x <- all0 %>% filter(Cal.Year == 2004, Month == 12)
# x <- Panel %>% filter(Cal.Year == 2004, Month == 12)


Panel = merge(all0, all, by = c("State", "Cal.Year", "Month","Formatted.Date","Region","No.week","adj.factor"))
Panel = merge(Panel, emply, by = c("State", "Cal.Year", "Month"))
Panel = merge(Panel, data_UI_SSA, by = c("State", "Cal.Year", "Month"), all.x = TRUE)

Panel = Panel[order(Panel$State, Panel$Cal.Year, Panel$Month), ] # make the order of months correct

Panel = Panel[Panel$State != "PR",]    # Remove Puerto Rico
Panel$State = factor(Panel$State)      # Redefine the factor levels

# make the panel balanced. 
Panel$index = 0
for(i in levels(Panel$State)) Panel$index[Panel$State == i] = 1:nrow(Panel[Panel$State == i,])
index.min = min(aggregate(index ~ State, data = Panel, max)[,2])
Panel = Panel[Panel$index <= index.min, ]
Panel = MoveFront(Panel, c("State", "index"))


#Creating Log variables. 

Panel = transform(Panel,  
                    lTotal      = log(Total),
                    lTitle.2    = log(Title.2),
                    lTitle.16   = log(Title.16),
                    lConcurrent = log(Concurrent),
                    
                    lunemply_S   = log(unemply_S),
                    lunemply_U   = log(unemply_U),
                    lemply_S     = log(emply_S),
                    lemply_U     = log(emply_U),
                    llabor_S     = log(labor_S),
                    llabor_U     = log(labor_U)
                    )

# Creating lags of log 

# Panel = pdata.frame(Panel, c("State","index"))
# 
# Panel$LlTotal       = lag(Panel$lTotal)
# Panel$LlTitle.2     = lag(Panel$lTitle.2)
# Panel$LlTitle.16    = lag(Panel$lTitle.16)
# Panel$LlConcurrent  = lag(Panel$lConcurrent)
# 
# Panel$Llunemply_S   = lag(Panel$lunemply_S)
# Panel$Llunemply_U   = lag(Panel$lunemply_U)
# Panel$Llemply_S     = lag(Panel$lemply_S)
# Panel$Llemply_U     = lag(Panel$lemply_U)
# Panel$Lllabor_S     = lag(Panel$llabor_S)
# Panel$Lllabor_U     = lag(Panel$llabor_U)
# 
# 
# #Creating Log differenced variables.
# 
# Panel$dlTotal       = diff(Panel$lTotal)
# Panel$dlTitle.2     = diff(Panel$lTitle.2)
# Panel$dlTitle.16    = diff(Panel$lTitle.16)
# Panel$dlConcurrent  = diff(Panel$lConcurrent)
# 
# Panel$dlunemply_S   = diff(Panel$lunemply_S)
# Panel$dlunemply_U   = diff(Panel$lunemply_U)
# Panel$dlemply_S     = diff(Panel$lemply_S)
# Panel$dlemply_U     = diff(Panel$lemply_U)
# Panel$dllabor_S     = diff(Panel$llabor_S)
# Panel$dllabor_U     = diff(Panel$llabor_U)
# 
# # Creating lags of log difference
# 
# # 1st Lag
# Panel$LdlTotal       = lag(Panel$dlTotal)
# Panel$LdlTitle.2     = lag(Panel$dlTitle.2)
# Panel$LdlTitle.16    = lag(Panel$dlTitle.16)
# Panel$LdlConcurrent  = lag(Panel$dlConcurrent)
# 
# Panel$Ldlunemply_S   = lag(Panel$dlunemply_S)
# Panel$Ldlunemply_U   = lag(Panel$dlunemply_U)
# Panel$Ldlemply_S     = lag(Panel$dlemply_S)
# Panel$Ldlemply_U     = lag(Panel$dlemply_U)
# Panel$Ldllabor_S     = lag(Panel$dllabor_S)
# Panel$Ldllabor_U     = lag(Panel$dllabor_U)
# 
# # 2nd Lag
# Panel$L2dlTotal       = lag(Panel$dlTotal, 2)
# Panel$L2dlTitle.2     = lag(Panel$dlTitle.2, 2)
# Panel$L2dlTitle.16    = lag(Panel$dlTitle.16, 2)
# Panel$L2dlConcurrent  = lag(Panel$dlConcurrent, 2)
# 
# Panel$L2dlunemply_S   = lag(Panel$dlunemply_S, 2)
# Panel$L2dlunemply_U   = lag(Panel$dlunemply_U, 2)
# Panel$L2dlemply_S     = lag(Panel$dlemply_S, 2)
# Panel$L2dlemply_U     = lag(Panel$dlemply_U, 2)
# Panel$L2dllabor_S     = lag(Panel$dllabor_S, 2)
# Panel$L2dllabor_U     = lag(Panel$dllabor_U, 2)
# 
# # 3rd Lag
# Panel$L3dlTotal       = lag(Panel$dlTotal, 3)
# Panel$L3dlTitle.2     = lag(Panel$dlTitle.2, 3)
# Panel$L3dlTitle.16    = lag(Panel$dlTitle.16, 3)
# Panel$L3dlConcurrent  = lag(Panel$dlConcurrent, 3)
# 
# Panel$L3dlunemply_S   = lag(Panel$dlunemply_S, 3)
# Panel$L3dlunemply_U   = lag(Panel$dlunemply_U, 3)
# Panel$L3dlemply_S     = lag(Panel$dlemply_S, 3)
# Panel$L3dlemply_U     = lag(Panel$dlemply_U, 3)
# Panel$L3dllabor_S     = lag(Panel$dllabor_S, 3)
# Panel$L3dllabor_U     = lag(Panel$dllabor_U, 3)
# 
# #fix(Panel)
# 
# Panel = as.data.frame(Panel)
# Panel$index = as.numeric(Panel$index)


## Creating application series net of OLS seasonal dummies. 



save(Panel, file = "Data/Panel.RData")


# 
# # Create a data frame for seasonal model, reg.data ----------------------------------- 
# 
# load("all.RData" )
# load("emply.RData")
# 
# reg.data = merge(all.same, emply[!names(emply) %in% "Formatted.Date"], by = c("State", "Cal.Year","Month"))
# 
# reg.data$State = as.factor(levels(reg.data$State)[reg.data$State])
# reg.data$Cal.Year = as.factor(reg.data$Cal.Year)
# 
#   ## Adjustment for outlier in Nov 2000 in NJ
# 
# reg.data[reg.data$State == "NJ" & reg.data$Cal.Year == "2000" & reg.data$Month == "11", c("Total","Title.2", "Title.16", "Concurrent","DI", "SSI")] = 
#   aaply(as.matrix(with(reg.data, reg.data[State == "NJ" & Cal.Year %in% c("2001","2002","2003") & Month == "11", c("Total","Title.2", "Title.16", "Concurrent", "DI", "SSI")])),
#         2, mean)
# 
# 
# reg.data = transform(reg.data,  State = as.factor(levels(State)[State]),
#                                 Cal.Year = as.factor(Cal.Year),
#                                 Month = as.factor(Month),
#                                 lTotal = log(Total),
#                                 lTitle.2 = log(Title.2),
#                                 lTitle.16 = log(Title.16),
#                                 lConcurrent = log(Concurrent),
#                                 lDI = log(DI),
#                                 lSSI = log(SSI),
#                                 lemply_U = log(emply_U),
#                                 lunemply_U = log(unemply_U)
#                                   )
# reg.data = reg.data[order(reg.data$State,reg.data$Cal.Year,reg.data$Month),]
# 
# reg.data$index = rep(1:(nrow(reg.data)/length(levels(reg.data$State))), length(levels(reg.data$State)))
# 
# # Create 1 month lag for all logged variables
# 
# reg.data = slide(reg.data, Var= "lTotal", NewVar = "LlTotal", GroupVar = "State", slideBy = -1)
# reg.data = slide(reg.data, Var= "lTitle.2", NewVar = "LlTitle.2", GroupVar = "State", slideBy = -1)
# reg.data = slide(reg.data, Var= "lTitle.16", NewVar = "LlTitle.16", GroupVar = "State", slideBy = -1)
# reg.data = slide(reg.data, Var= "lConcurrent", NewVar = "LlConcurrent", GroupVar = "State", slideBy = -1)
# reg.data = slide(reg.data, Var= "lDI", NewVar = "LlDI", GroupVar = "State", slideBy = -1)
# reg.data = slide(reg.data, Var= "lSSI", NewVar = "LlSSI", GroupVar = "State", slideBy = -1)
# reg.data = slide(reg.data, Var= "lemply_U", NewVar = "Llemply_U", GroupVar = "State", slideBy = -1)
# reg.data = slide(reg.data, Var= "lunemply_U", NewVar = "Llunemply_U", GroupVar = "State", slideBy = -1)
# 
# reg.data = transform(reg.data, dlTotal = lTotal - LlTotal,
#                                dlTitle.2 = lTitle.2 - LlTitle.2,
#                                dlTitle.16 = lTitle.16 - LlTitle.16,
#                                dlConcurrent = lConcurrent - LlConcurrent,
#                                dlDI = lDI - LlDI,
#                                dlSSI = lSSI - LlSSI,
#                                dlemply_U = lemply_U - Llemply_U,
#                                dlunemply_U = lunemply_U - Llunemply_U
#                      )
# 
# reg.data = slide(reg.data, Var= "dlemply_U", NewVar = "Ldlemply_U", GroupVar = "State", slideBy = -1)
# reg.data = slide(reg.data, Var= "dlunemply_U", NewVar = "Ldlunemply_U", GroupVar = "State", slideBy = -1)
# 
# reg.data = slide(reg.data, Var= "dlemply_U", NewVar = "L2dlemply_U", GroupVar = "State", slideBy = -2)
# reg.data = slide(reg.data, Var= "dlunemply_U", NewVar = "L2dlunemply_U", GroupVar = "State", slideBy = -2)
# 
# reg.data = slide(reg.data, Var= "Month", NewVar = "LMonth", GroupVar = "State", slideBy = -1)
# reg.data = slide(reg.data, Var= "Month", NewVar = "L2Month", GroupVar = "State", slideBy = -2)
# reg.data = slide(reg.data, Var= "Month", NewVar = "L3Month", GroupVar = "State", slideBy = -3)
# 
# reg.data = transform(reg.data, LMonth = as.factor(LMonth),
#                                L2Month = as.factor(L2Month),
#                                L3Month  = as.factor(L3Month))
# 
# # # Construct Month varialbe for each states, they are to be used in unrestricted models
# # var.month = reg.data$Month[reg.data$State == "NW"]
# # row.num = nrow(reg.data)
# # col.num = length(levels(reg.data$State))
# # 
# # month.matrix = matrix(0,row.num,col.num)
# # for (i in 1:(col.num))
# #   month.matrix[((i-1)*148+1):((i-1)*148+148),i] = var.month
# # 
# # colnames(month.matrix) = paste0("Month.",levels(reg.data$State))
# # month.matrix = as.data.frame(month.matrix)
# # for(i in 1:ncol(month.matrix))
# #   month.matrix[,i] = as.factor(month.matrix[,i])
# # 
# # reg.data = data.frame(reg.data, month.matrix)
# # 
# # 
# # # Construct 53*12 dummy variables, which are cross terms of Month and State
# # dummy.matrix = model.matrix(~Month:State, data = reg.data)[,-1]
# # colnames(dummy.matrix) = sub(':','.', colnames(dummy.matrix))
# # 
# # reg.data.ex = data.frame(reg.data, dummy.matrix)
# # 
# # # Generate a character of variable names used in regression formula
# # var.month.state = colnames(dummy.matrix)
# # 
# # # fmla.ex = "~"
# # # for (i in 1:length(var.month.state)) fmla.ex = paste(fmla.ex, var.month.state[i],"+")
# 
# 
# # remove temporary variables
# rm(var.month,row.num, col.num, month.matrix, dummy.matrix)
# 
# save(reg.data, file = "reg.data.RData")
# 
# # Create a data frame for panel data/ spatial model, panel.data ----------------------------------- 
# 
# load("reg.data.RData")
# load("all.SA.df.RData")
# load("all.SA.same.RData")
# load("all.SA.same.dl.RData")
# load("all.RData")
# 
# # Construct data frames
# panel.d = subset(reg.data, !State %in% c("PR"), select = c("State", "index", "Region", "State","Cal.Year","Month","Formatted.Date"))
# panel.s = subset(reg.data, !State %in% c("PR"), select = c("State","index", "Region", "State","Cal.Year","Month","Formatted.Date"))
# 
# types = c("Total", "Title.2", "Title.16", "Concurrent")
# index = c("State","Formatted.Date")
# SA = c("d10","d11","d12")
# 
# state.select = c("AG","A8","A9", states52)
# 
# # Extract Components
# original = subset(all0,     State %in% state.select, select = c(index, types) )
# all.df   = subset(all,      State %in% state.select, select = c(index, types) )
# all.same = subset(all.same, State %in% state.select, select = c(index, types) )
# 
# SA.Total    = subset(all.SA.Total,    State %in% state.select, select = c(index, SA))
# SA.Total.df = subset(all.SA.Total.df, State %in% state.select, select = c(index, SA))
# SA.dlTotal  = subset(all.SA.dlTotal,  State %in% state.select, select = c(index, SA))
# 
# SA.Title.2    = subset(all.SA.Title.2,    State %in% state.select, select = c(index, SA))
# SA.Title.2.df = subset(all.SA.Title.2.df, State %in% state.select, select = c(index, SA))
# SA.dlTitle.2 = subset(all.SA.dlTitle.2,  State %in% state.select, select = c(index, SA))
# 
# SA.Title.16    = subset(all.SA.Title.16,    State %in% state.select, select = c(index, SA))
# SA.Title.16.df = subset(all.SA.Title.16.df, State %in% state.select, select = c(index, SA))
# SA.dlTitle.16   = subset(all.SA.dlTitle.16,   State %in% state.select, select = c(index, SA))
# 
# SA.Concurrent    = subset(all.SA.Concurrent,    State %in% state.select, select = c(index, SA))
# SA.Concurrent.df = subset(all.SA.Concurrent.df, State %in% state.select, select = c(index, SA))
# SA.dlConcurrent  = subset(all.SA.dlConcurrent,  State %in% state.select, select = c(index, SA))
# 
# # Rename Variables
# original = rename(original, c("Total" = "Total.0", "Title.2" = "Title.2.0", "Title.16" = "Title.16.0", "Concurrent" = "Concurrent.0"))
# all.df   = rename(all.df, c("Total" = "Total.df", "Title.2" = "Title.2.df", "Title.16" = "Title.16.df", "Concurrent" = "Concurrent.df"))
# all.same   = rename(all.same, c("Total" = "Total.same", "Title.2" = "Title.2.same", "Title.16" = "Title.16.same", "Concurrent" = "Concurrent.same"))
# 
# SA.Total    = rename(SA.Total, c("d10" = "Total.factor", "d11" = "Total.adj", "d12" = "Total.trend"))
# SA.Total.df = rename(SA.Total.df, c("d10" = "Total.factor", "d11" = "Total.adj", "d12" = "Total.trend"))
# SA.dlTotal  = rename(SA.dlTotal, c("d10" = "dlTotal.factor", "d11" = "sdlTotal", "d12" = "dlTotal.trend"))
# 
# 
# SA.Title.2   = rename(SA.Title.2, c("d10" = "Title.2.factor", "d11" = "Title.2.adj", "d12" = "Title.2.trend"))
# SA.Title.2.df   = rename(SA.Title.2.df, c("d10" = "Title.2.factor", "d11" = "Title.2.adj", "d12" = "Title.2.trend"))
# SA.dlTitle.2   = rename(SA.dlTitle.2, c("d10" = "dlTitle.2.factor", "d11" = "sdlTitle.2", "d12" = "dlTitle.2.trend"))
# 
# SA.Title.16   = rename(SA.Title.16, c("d10" = "Title.16.factor", "d11" = "Title.16.adj", "d12" = "Title.16.trend"))
# SA.Title.16.df   = rename(SA.Title.16.df, c("d10" = "Title.16.factor", "d11" = "Title.16.adj", "d12" = "Title.16.trend"))
# SA.dlTitle.16   = rename(SA.dlTitle.16, c("d10" = "dlTitle.16.factor", "d11" = "sdlTitle.16", "d12" = "dlTitle.16.trend"))
# 
# SA.Concurrent   = rename(SA.Concurrent, c("d10" = "Concurrent.factor", "d11" = "Concurrent.adj", "d12" = "Concurrent.trend"))
# SA.Concurrent.df   = rename(SA.Concurrent.df, c("d10" = "Concurrent.factor", "d11" = "Concurrent.adj", "d12" = "Concurrent.trend"))
# SA.dlConcurrent   = rename(SA.dlConcurrent, c("d10" = "dlConcurrent.factor", "d11" = "sdlConcurrent", "d12" = "dlConcurrent.trend"))
# 
# # Merge data. 
# panel.d = merge(panel.d, original, by = c("State","Formatted.Date"))
# panel.d = merge(panel.d, all.df, by = c("State","Formatted.Date"))
# panel.d = merge(panel.d, SA.Total.df, by = c("State","Formatted.Date"))
# panel.d = merge(panel.d, SA.Title.2.df, by = c("State","Formatted.Date"))
# panel.d = merge(panel.d, SA.Title.16.df, by = c("State","Formatted.Date"))
# panel.d = merge(panel.d, SA.Concurrent.df, by = c("State","Formatted.Date"))
# 
# panel.s = merge(panel.s, original, by = c("State","Formatted.Date"))
# panel.s = merge(panel.s, all.same, by = c("State","Formatted.Date"))
# panel.s = merge(panel.s, SA.Total, by = c("State","Formatted.Date"))
# panel.s = merge(panel.s, SA.Title.2, by = c("State","Formatted.Date"))
# panel.s = merge(panel.s, SA.Title.16, by = c("State","Formatted.Date"))
# panel.s = merge(panel.s, SA.Concurrent, by = c("State","Formatted.Date"))
# panel.s = merge(panel.s, SA.dlTotal, by = c("State","Formatted.Date"), all.x = TRUE)
# panel.s = merge(panel.s, SA.dlTitle.2, by = c("State","Formatted.Date"), all.x = TRUE)
# panel.s = merge(panel.s, SA.dlTitle.16, by = c("State","Formatted.Date"), all.x = TRUE)
# panel.s = merge(panel.s, SA.dlConcurrent, by = c("State","Formatted.Date"), all.x = TRUE)
# 
# 
# 
# # Merge with the employment data 
# 
# select.emply = c(index, "uRate_S",   "uRate_U",
#                  "unemply_S", "unemply_U", 
#                  "emply_S",   "emply_U", 
#                  "labor_S",   "labor_U",
#                  "unemply1_S", "unemply2_S", "unemply3_S"
#                  )
# 
# panel.d = merge(panel.d, subset(reg.data, select = select.emply), by = index)
# panel.s = merge(panel.s, subset(reg.data, select = select.emply), by = index)
# 
# panel.s = transform(panel.s, unemply12_S = unemply1_S + unemply2_S,
#                    unemply123_S = unemply1_S + unemply2_S + unemply3_S)
# 
# 
# 
# # Creating variables.
# 
#  # Creating log variables
# panel.d = transform(panel.d, lTotal.df    = log(Total.df),
#                              lTitle.2.df  = log(Title.2.df),
#                              lTitle.16.df = log(Title.16.df),
#                              lConcurrent.df = log(Concurrent.df),
#                              lTotal.adj   = log(Total.adj),
#                              lTitle.2.adj = log(Title.2.adj),
#                              lTitle.16.adj= log(Title.16.adj),
#                              lConcurrent.adj = log(Concurrent.adj),
#                              lunemply_S   = log(unemply_S),
#                              lunemply_U   = log(unemply_U),
#                              lemply_S     = log(emply_S),
#                              lemply_U     = log(emply_U),
#                              llabor_S     = log(labor_S),
#                              llabor_U     = log(labor_U)
#                              )
# 
# panel.s = transform(panel.s,  lTotal.s    = log(Total.same),
#                               lTitle.2.s  = log(Title.2.same),
#                               lTitle.16.s = log(Title.16.same),
#                               lConcurrent.s = log(Concurrent.same),
#                               lTotal.adj   = log(Total.adj),
#                               lTitle.2.adj = log(Title.2.adj),
#                               lTitle.16.adj= log(Title.16.adj),
#                               lConcurrent.adj = log(Concurrent.adj),
#                               lunemply_S   = log(unemply_S),
#                               lunemply_U   = log(unemply_U),
#                               lemply_S     = log(emply_S),
#                               lemply_U     = log(emply_U),
#                               llabor_S     = log(labor_S),
#                               llabor_U     = log(labor_U),
#                               lunemply1_S   = log(unemply1_S),
#                               lunemply2_S   = log(unemply2_S),
#                               lunemply3_S   = log(unemply3_S),
#                               lunemply12_S   = log(unemply12_S),
#                               lunemply123_S   = log(unemply123_S))
# 
# # Creating lags of log variables 
# ##
# panel.d = slide(panel.d, Var= "lTotal.df", NewVar = "LlTotal.df", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "lTitle.2.df", NewVar = "LlTitle.2.df", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "lTitle.16.df", NewVar = "LlTitle.16.df", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "lConcurrent.df", NewVar = "LlConcurrent.df", GroupVar = "State", slideBy = -1)
# 
# panel.d = slide(panel.d, Var= "lTotal.adj", NewVar = "LlTotal.adj", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "lTitle.2.adj", NewVar = "LlTitle.2.adj", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "lTitle.16.adj", NewVar = "LlTitle.16.adj", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "lConcurrent.adj", NewVar = "LlConcurrent.adj", GroupVar = "State", slideBy = -1)
# 
# panel.d = slide(panel.d, Var= "lunemply_S", NewVar = "Llunemply_S", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "lunemply_U", NewVar = "Llunemply_U", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "lemply_S",   NewVar = "Llemply_S",   GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "lemply_U",   NewVar = "Llemply_U",   GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "llabor_S",   NewVar = "Lllabor_S",   GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "llabor_U",   NewVar = "Lllabor_U",   GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "uRate_S",    NewVar = "LuRate_S",    GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "uRate_U",    NewVar = "LuRate_U",    GroupVar = "State", slideBy = -1)
# 
# ##
# panel.s = slide(panel.s, Var= "lTotal.s", NewVar = "LlTotal.s", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lTitle.2.s", NewVar = "LlTitle.2.s", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lTitle.16.s", NewVar = "LlTitle.16.s", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lConcurrent.s", NewVar = "LlConcurrent.s", GroupVar = "State", slideBy = -1)
# 
# panel.s = slide(panel.s, Var= "lTotal.adj", NewVar = "LlTotal.adj", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lTitle.2.adj", NewVar = "LlTitle.2.adj", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lTitle.16.adj", NewVar = "LlTitle.16.adj", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lConcurrent.adj", NewVar = "LlConcurrent.adj", GroupVar = "State", slideBy = -1)
# 
# panel.s = slide(panel.s, Var= "lunemply_S", NewVar = "Llunemply_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lunemply_U", NewVar = "Llunemply_U", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lemply_S",   NewVar = "Llemply_S",   GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lemply_U",   NewVar = "Llemply_U",   GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "llabor_S",   NewVar = "Lllabor_S",   GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "llabor_U",   NewVar = "Lllabor_U",   GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "uRate_S",    NewVar = "LuRate_S",    GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "uRate_U",    NewVar = "LuRate_U",    GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lunemply1_S", NewVar = "Llunemply1_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lunemply2_S", NewVar = "Llunemply2_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lunemply3_S", NewVar = "Llunemply3_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lunemply12_S", NewVar = "Llunemply12_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lunemply123_S", NewVar = "Llunemply123_S", GroupVar = "State", slideBy = -1)
# 
#  # Creating log growth rates/difference. 
# panel.d = transform(panel.d,  dlTotal.df     = lTotal.df - LlTotal.df,
#                               dlTitle.2.df   = lTitle.2.df - LlTitle.2.df,
#                               dlTitle.16.df  = lTitle.16.df - LlTitle.16.df,
#                               dlConcurrent.df = lConcurrent.df - LlConcurrent.df,
#                               dlTotal.adj   = lTotal.adj - LlTotal.adj,
#                               dlTitle.2.adj = lTitle.2.adj - LlTitle.2.adj,
#                               dlTitle.16.adj= lTitle.16.adj - LlTitle.16.adj,
#                               dlConcurrent.adj = lConcurrent.adj - LlConcurrent.adj,
#                               dlunemply_S   =  lunemply_S - Llunemply_S,
#                               dlunemply_U   =  lunemply_U - Llunemply_U,
#                               dlemply_S     =  lemply_S - Llemply_S,
#                               dlemply_U     =  lemply_U - Llemply_U,
#                               dllabor_S     =  llabor_S - Lllabor_S,
#                               dllabor_U     =  llabor_U - Lllabor_U,
#                               duRate_S      =  uRate_S - LuRate_S,
#                               duRate_U      =  uRate_U - LuRate_U)
# 
# panel.s = transform(panel.s,  dlTotal.s     = lTotal.s - LlTotal.s,
#                               dlTitle.2.s   = lTitle.2.s - LlTitle.2.s,
#                               dlTitle.16.s  = lTitle.16.s - LlTitle.16.s,
#                               dlConcurrent.s = lConcurrent.s - LlConcurrent.s,
#                               dlTotal.adj   = lTotal.adj - LlTotal.adj,
#                               dlTitle.2.adj = lTitle.2.adj - LlTitle.2.adj,
#                               dlTitle.16.adj= lTitle.16.adj - LlTitle.16.adj,
#                               dlConcurrent.adj = lConcurrent.adj - LlConcurrent.adj,
#                               dlunemply_S   =  lunemply_S - Llunemply_S,
#                               dlunemply_U   =  lunemply_U - Llunemply_U,
#                               dlemply_S     =  lemply_S - Llemply_S,
#                               dlemply_U     =  lemply_U - Llemply_U,
#                               dllabor_S     =  llabor_S - Lllabor_S,
#                               dllabor_U     =  llabor_U - Lllabor_U,
#                               duRate_S      =  uRate_S - LuRate_S,
#                               duRate_U      =  uRate_U - LuRate_U,
#                               dlunemply1_S   =  lunemply1_S - Llunemply1_S,
#                               dlunemply2_S   =  lunemply2_S - Llunemply2_S,
#                               dlunemply3_S   =  lunemply3_S - Llunemply3_S,
#                               dlunemply12_S   =  lunemply12_S - Llunemply12_S,
#                               dlunemply123_S   =  lunemply123_S - Llunemply123_S)
# 
# # Creating the lag of Log growth rates/difference
# 
# panel.d = slide(panel.d, Var= "dlTotal.df", NewVar = "LdlTotal.df", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "dlTitle.2.df", NewVar = "LdlTitle.2.df", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "dlTitle.16.df", NewVar = "LdlTitle.16.df", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "dlConcurrent.df", NewVar = "LdlConcurrent.df", GroupVar = "State", slideBy = -1)
# 
# panel.d = slide(panel.d, Var= "dlTotal.adj", NewVar = "LdlTotal.adj", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "dlTitle.2.adj", NewVar = "LdlTitle.2.adj", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "dlTitle.16.adj", NewVar = "LdlTitle.16.adj", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "dlConcurrent.adj", NewVar = "LdlConcurrent.adj", GroupVar = "State", slideBy = -1)
# 
# panel.d = slide(panel.d, Var= "dlunemply_S", NewVar = "Ldlunemply_S", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "dlunemply_U", NewVar = "Ldlunemply_U", GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "dlemply_S",   NewVar = "Ldlemply_S",   GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "dlemply_U",   NewVar = "Ldlemply_U",   GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "dllabor_S",   NewVar = "Ldllabor_S",   GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "dllabor_U",   NewVar = "Ldllabor_U",   GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "duRate_S",    NewVar = "LduRate_S",    GroupVar = "State", slideBy = -1)
# panel.d = slide(panel.d, Var= "duRate_U",    NewVar = "LduRate_U",    GroupVar = "State", slideBy = -1)
# 
# ##
# panel.s = slide(panel.s, Var= "dlTotal.s", NewVar = "LdlTotal.s", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlTitle.2.s", NewVar = "LdlTitle.2.s", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlTitle.16.s", NewVar = "LdlTitle.16.s", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlConcurrent.s", NewVar = "LdlConcurrent.s", GroupVar = "State", slideBy = -1)
# 
# panel.s = slide(panel.s, Var= "dlTotal.adj", NewVar = "LdlTotal.adj", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlTitle.2.adj", NewVar = "LdlTitle.2.adj", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlTitle.16.adj", NewVar = "LdlTitle.16.adj", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlConcurrent.adj", NewVar = "LdlConcurrent.adj", GroupVar = "State", slideBy = -1)
# 
# panel.s = slide(panel.s, Var= "sdlTotal", NewVar = "LsdlTotal", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "sdlTitle.2", NewVar = "LsdlTitle.2", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "sdlTitle.16", NewVar = "LsdlTitle.16", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "sdlConcurrent", NewVar = "LsdlConcurrent", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "sdlTotal", NewVar = "L2sdlTotal", GroupVar = "State", slideBy = -2) # for regression
# panel.s = slide(panel.s, Var= "sdlTotal", NewVar = "L3sdlTotal", GroupVar = "State", slideBy = -3) # for regression
# 
# panel.s = slide(panel.s, Var= "dlunemply_S", NewVar = "Ldlunemply_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlunemply_S", NewVar = "L2dlunemply_S", GroupVar = "State", slideBy = -2) # for regression
# panel.s = slide(panel.s, Var= "dlunemply_S", NewVar = "L3dlunemply_S", GroupVar = "State", slideBy = -3) # for regression
# panel.s = slide(panel.s, Var= "dlunemply_U", NewVar = "Ldlunemply_U", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlemply_S",   NewVar = "Ldlemply_S",   GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlemply_U",   NewVar = "Ldlemply_U",   GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dllabor_S",   NewVar = "Ldllabor_S",   GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dllabor_U",   NewVar = "Ldllabor_U",   GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "duRate_S",    NewVar = "LduRate_S",    GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "duRate_U",    NewVar = "LduRate_U",    GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlunemply1_S", NewVar = "Ldlunemply1_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlunemply2_S", NewVar = "Ldlunemply2_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlunemply3_S", NewVar = "Ldlunemply3_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlunemply12_S", NewVar = "Ldlunemply12_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlunemply123_S", NewVar = "Ldlunemply123_S", GroupVar = "State", slideBy = -1)
# 
# 
# 
# 
# 
# # setting index
# 
# panel.d = subset(panel.d, select = names(panel.d)[c(1,3,4,2,5:length(names(panel.d)))])
# panel.d = transform(panel.d, Formatted.Date = as.yearmon(Formatted.Date))
# 
# panel.D = pdata.frame(panel.d, index = c("State","index"), row.names = TRUE)
# summary(panel.D$Total.df)
# 
# 
# panel.s = subset(panel.s, select = names(panel.s)[c(1,3,4,2,5:length(names(panel.s)))]  )
# panel.s = transform(panel.s, Formatted.Date = as.yearmon(Formatted.Date))
# 
# panel.S = pdata.frame(panel.s, index = c("State","index"), row.names = TRUE)
# summary(panel.S$Total.same)
# 
# ## adding 132 and 133 as outliers
# 
# panel.s$o132 = panel.s$index == 132
# panel.s$o133 = panel.s$index == 133
# 
# ## national unemployment rate variable
# 
# panel.s$Nunemply_S = subset(panel.s, State == "NW", select = c("unemply_S"))[[1]]
# panel.s$NuRate_S   = subset(panel.s, State == "NW", select = c("uRate_S"))[[1]]
# panel.s$Nemply_S   = subset(panel.s, State == "NW", select = c("emply_S"))[[1]]
# 
# panel.s = transform(panel.s, lNunemply_S = log(Nunemply_S),
#                              lNuRate_S   = log(NuRate_S),
#                              lNemply_S   = log(Nemply_S))
# 
# panel.s = slide(panel.s, Var= "lNunemply_S", NewVar = "LlNunemply_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lNemply_S", NewVar = "LlNemply_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "lNuRate_S", NewVar = "LlNuRate_S", GroupVar = "State", slideBy = -1)
# 
# panel.s = transform(panel.s, dlNunemply_S = lNunemply_S - LlNunemply_S,
#                              dlNuRate_S   = lNuRate_S - LlNuRate_S,
#                              dlNemply_S   = lNemply_S - LlNemply_S)
# 
# panel.s = transform(panel.s, dlNunemply_S = lNunemply_S - LlNunemply_S,
#                              dlNuRate_S   = lNuRate_S - LlNuRate_S,
#                              dlNemply_S   = lNemply_S - LlNemply_S)
# 
# panel.s = slide(panel.s, Var= "dlNunemply_S", NewVar = "LdlNunemply_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlNemply_S", NewVar = "LdlNemply_S", GroupVar = "State", slideBy = -1)
# panel.s = slide(panel.s, Var= "dlNuRate_S", NewVar = "LdlNuRate_S", GroupVar = "State", slideBy = -1)
# 
# 
# 
# #Cleaning up.
# rm(original,
#    SA.Title.16, SA.Title.16.df,
#    SA.Title.2 , SA.Title.2.df,
#    SA.Concurrent, SA.Concurrent.df,
#    SA.dlTitle.2, SA.dlTitle.16,
#    SA,dlTotal, SA.dlConcurrent,
#    SA.Total, SA.Total.df,
#    all.SA.Title.16, all.SA.Title.16.df,
#    all.SA.Title.2 , all.SA.Title.2.df,
#    all.SA.Concurrent, all.SA.Concurrent.df,
#    all.SA.Total, all.SA.Total.df,
#    all.SA.DI, all.SA.SSI,
#    all.SA.dlTotal,
#    all.SA.dlTitle.2, all.SA.dlTitle.16,
#    all.SA.dlConcurrent,
#    all, all0, all.df, all.same
#    )
# 
# save(panel.d, panel.s, panel.D, file = "panel.RData")

