# A summary of data files------------------------------
  # 1. all.RData:
      # Generated by: Data.import.MOWL.R
      # Data frame included:
        # all0: Original MOWL data with Total, SSI only, SSDI only, SSI, SSDI applications at national  and state levels
        # all : The same as all0, but all data entries are adjusted for the length of "SSA working month"
  
  # 2. emply.RData
      # generated by: Data.import.BLS.R
      # Dataframe:
        # emply: Sesonally adjusted and unadjusted series of unemployment rate, -
        #        unemployment, employment, and labor force, at state and national level. 
      #Note: all types of national levels are the same: the original data from BLS that is -
        #        calculated based on all states. 
 
  # 3. panel.RData
      # Generated by Data.Combine.R
      # Dataframe:
        # Panel: Combine data from "all0" and "all" in "all.RData" and "emply" in "emply.RData",
        #        log, log difference, and lags are generated. 



source("General.R")

(load("Data/all.RData"))
(load("Data/emply.RData"))
(load("Data/data_UI_SSA.RData"))
(load("Data/jobOpen.RData"))
(load("Data/data_emplyMon.RData")) # CES empllyment by industry and state


data_UI_SSA <- 
  dplyr::select(data_UI_SSA, State = state, Cal.Year = year, Month = month, UIIC, UICC, UIIC_unadj, UICC_unadj)

data_jobOpen <- 
  dplyr::select(data_jobOpen, Cal.Year = year, Month = month, everything())

data_emplyMon <- 
  dplyr::select(data_emplyMon, Cal.Year = year, Month = month, everything())


# emply$State %>% unique
# data_UI_SSA$state %>% unique()
# data_emplyMon$State %>% unique()

# Note:
# - All data frames should contains a group for national total with the name "AG". 

#Panel$Formatted.Date %>% unique

Panel = merge(all0,  all,           by = c("State", "Cal.Year", "Month","Formatted.Date","Region","No.week","adj.factor"), all.x = TRUE)
Panel = merge(Panel, emply,         by = c("State", "Cal.Year", "Month"), all.x = TRUE)
Panel = merge(Panel, data_UI_SSA,   by = c("State", "Cal.Year", "Month"), all.x = TRUE)
Panel = merge(Panel, data_jobOpen,  by = c("Cal.Year", "Month"), all.x = TRUE)
Panel = merge(Panel, data_emplyMon, by = c("State", "Cal.Year", "Month"), all.x = TRUE)

Panel = Panel[order(Panel$State, Panel$Cal.Year, Panel$Month), ] # make the order of months correct

Panel = Panel[!Panel$State %in% c("PR", "GU"), ]    # Remove Puerto Rico and Guam
Panel$State = factor(Panel$State)      # Redefine the factor levels

# make the panel balanced. (Not used)
# Panel$index = 0
# for(i in levels(Panel$State)) Panel$index[Panel$State == i] = 1:nrow(Panel[Panel$State == i,])
# index.min = min(aggregate(index ~ State, data = Panel, max)[,2])
#Panel = Panel[Panel$index <= index.min, ]
Panel = MoveFront(Panel, c("State"))


#Creating Log variables. 

Panel = transform(Panel,  
                    lTotal      = log(Total),
                    lTitle.2    = log(Title.2),
                    lTitle.16   = log(Title.16),
                    lConcurrent = log(Concurrent),
                    
                    lunemply_S   = log(unemply_S),
                    lunemply_U   = log(unemply_U),
                    lemply_S     = log(emply_S),
                    lemply_U     = log(emply_U),
                    llabor_S     = log(labor_S),
                    llabor_U     = log(labor_U)
                    )

# Creating lags of log 
{
# Panel = pdata.frame(Panel, c("State","index"))
# 
# Panel$LlTotal       = lag(Panel$lTotal)
# Panel$LlTitle.2     = lag(Panel$lTitle.2)
# Panel$LlTitle.16    = lag(Panel$lTitle.16)
# Panel$LlConcurrent  = lag(Panel$lConcurrent)
# 
# Panel$Llunemply_S   = lag(Panel$lunemply_S)
# Panel$Llunemply_U   = lag(Panel$lunemply_U)
# Panel$Llemply_S     = lag(Panel$lemply_S)
# Panel$Llemply_U     = lag(Panel$lemply_U)
# Panel$Lllabor_S     = lag(Panel$llabor_S)
# Panel$Lllabor_U     = lag(Panel$llabor_U)
# 
# 
# #Creating Log differenced variables.
# 
# Panel$dlTotal       = diff(Panel$lTotal)
# Panel$dlTitle.2     = diff(Panel$lTitle.2)
# Panel$dlTitle.16    = diff(Panel$lTitle.16)
# Panel$dlConcurrent  = diff(Panel$lConcurrent)
# 
# Panel$dlunemply_S   = diff(Panel$lunemply_S)
# Panel$dlunemply_U   = diff(Panel$lunemply_U)
# Panel$dlemply_S     = diff(Panel$lemply_S)
# Panel$dlemply_U     = diff(Panel$lemply_U)
# Panel$dllabor_S     = diff(Panel$llabor_S)
# Panel$dllabor_U     = diff(Panel$llabor_U)
# 
# # Creating lags of log difference
# 
# # 1st Lag
# Panel$LdlTotal       = lag(Panel$dlTotal)
# Panel$LdlTitle.2     = lag(Panel$dlTitle.2)
# Panel$LdlTitle.16    = lag(Panel$dlTitle.16)
# Panel$LdlConcurrent  = lag(Panel$dlConcurrent)
# 
# Panel$Ldlunemply_S   = lag(Panel$dlunemply_S)
# Panel$Ldlunemply_U   = lag(Panel$dlunemply_U)
# Panel$Ldlemply_S     = lag(Panel$dlemply_S)
# Panel$Ldlemply_U     = lag(Panel$dlemply_U)
# Panel$Ldllabor_S     = lag(Panel$dllabor_S)
# Panel$Ldllabor_U     = lag(Panel$dllabor_U)
# 
# # 2nd Lag
# Panel$L2dlTotal       = lag(Panel$dlTotal, 2)
# Panel$L2dlTitle.2     = lag(Panel$dlTitle.2, 2)
# Panel$L2dlTitle.16    = lag(Panel$dlTitle.16, 2)
# Panel$L2dlConcurrent  = lag(Panel$dlConcurrent, 2)
# 
# Panel$L2dlunemply_S   = lag(Panel$dlunemply_S, 2)
# Panel$L2dlunemply_U   = lag(Panel$dlunemply_U, 2)
# Panel$L2dlemply_S     = lag(Panel$dlemply_S, 2)
# Panel$L2dlemply_U     = lag(Panel$dlemply_U, 2)
# Panel$L2dllabor_S     = lag(Panel$dllabor_S, 2)
# Panel$L2dllabor_U     = lag(Panel$dllabor_U, 2)
# 
# # 3rd Lag
# Panel$L3dlTotal       = lag(Panel$dlTotal, 3)
# Panel$L3dlTitle.2     = lag(Panel$dlTitle.2, 3)
# Panel$L3dlTitle.16    = lag(Panel$dlTitle.16, 3)
# Panel$L3dlConcurrent  = lag(Panel$dlConcurrent, 3)
# 
# Panel$L3dlunemply_S   = lag(Panel$dlunemply_S, 3)
# Panel$L3dlunemply_U   = lag(Panel$dlunemply_U, 3)
# Panel$L3dlemply_S     = lag(Panel$dlemply_S, 3)
# Panel$L3dlemply_U     = lag(Panel$dlemply_U, 3)
# Panel$L3dllabor_S     = lag(Panel$dllabor_S, 3)
# Panel$L3dllabor_U     = lag(Panel$dllabor_U, 3)
# 
# #fix(Panel)
# 
# Panel = as.data.frame(Panel)
# Panel$index = as.numeric(Panel$index)
}

## Creating application series net of OLS seasonal dummies. 

save(Panel, file = "Data/Panel.RData")


